# Ren'Py GUI configuration
# Auto-generated by All Novel Can Be Galgame

init python:
    gui.about = "Generated by All Novel Can Be Galgame"

define gui.text_font = "DejaVuSans.ttf"
define gui.name_text_size = 22
define gui.text_size = 22
define gui.label_text_size = 22
define gui.notify_text_size = 18
define gui.title_text_size = 75

define gui.textbox_height = 278
define gui.textbox_yalign = 1.0

define gui.choice_button_width = 1185
define gui.choice_button_height = None
define gui.choice_button_tile = False
define gui.choice_button_text_font = "DejaVuSans.ttf"
define gui.choice_button_text_size = 22
define gui.choice_button_text_xalign = 0.5
define gui.choice_button_text_idle_color = "#ffffffcc"
define gui.choice_button_text_hover_color = "#ffffff"

define gui.navigation_xpos = 60
define gui.skip_indicator = True
define gui.about = _("Powered by All Novel Can Be Galgame")
