# Game options
# Auto-generated by All Novel Can Be Galgame

define config.name = _("{{GAME_TITLE}}")
define config.version = "1.0.0"

define gui.about = _("Generated by All Novel Can Be Galgame\\nBased on: {{GAME_TITLE}}")

define build.name = "{{GAME_NAME}}"
define build.directory = True
define build.classify("**~", None)
define build.classify("**.bak", None)
define build.classify("**/.**", None)
define build.classify("**/#**", None)
define build.classify("**/thumbs.db", None)
define build.classify("game/**.rpy", None)
define build.classify("**.psd", None)
define build.classify("game/cache/**", None)

init python:
    build.classify("**~", None)
    build.classify("**.bak", None)
    build.classify("**/.**", None)
    build.classify("**/#**", None)
    build.classify("**/thumbs.db", None)
    build.classify("game/**.rpy", None)
    build.classify("**.psd", None)
    build.classify("game/cache/**", None)
