# Default screens
# Auto-generated by All Novel Can Be Galgame

screen say(who, what):
    style_prefix "say"

    window:
        id "window"

        if who is not None:
            window:
                id "namebox"
                style "namebox"
                text who id "who"

        text what id "what"

    if not renpy.variant("small"):
        add SideImage() xalign 0.0 yalign 1.0

style window:
    xalign 0.5
    xfill True
    yalign gui.textbox_yalign
    ysize gui.textbox_height

style namebox:
    xpos gui.name_xpos
    xanchor gui.name_xalign
    xsize gui.namebox_width
    ypos gui.name_ypos
    ysize gui.namebox_height

    background Frame("gui/namebox.png", gui.namebox_borders, tile=gui.namebox_tile, xalign=gui.name_xalign)
    padding gui.namebox_borders.padding

style say_label:
    properties gui.text_properties("name", accent=True)
    xalign gui.name_xalign
    yalign 0.5

style say_dialogue:
    properties gui.text_properties("dialogue")
    xpos gui.text_xpos
    xanchor gui.text_xalign if "text_xalign" in dir(gui) else None
    xsize gui.text_width
    ypos gui.text_ypos
    text_align gui.text_xalign
    layout ("subtitle" if gui.text_xalign else "tex")

screen input(prompt):
    style_prefix "input"

    window:
        vbox:
            xanchor gui.text_xalign
            xpos gui.text_xpos
            xsize gui.text_width
            ypos gui.text_ypos

            text prompt style "input_prompt"
            input id "input"

style input_prompt:
    xalign gui.text_xalign
    properties gui.text_properties("input_prompt")

style input:
    xalign gui.text_xalign
    xmaximum gui.text_width

screen choice(items):
    vbox:
        style_prefix "choice"

        for i in items:
            textbutton i.caption action i.action

style choice_vbox:
    xalign 0.5
    ypos 405
    yanchor 0.5
    spacing 45

style choice_button is default:
    properties gui.button_properties("choice_button")

style choice_button_text is default:
    properties gui.button_text_properties("choice_button")

screen navigation():
    vbox:
        style_prefix "navigation"

        xpos gui.navigation_xpos
        yalign 0.5
        spacing 6

        textbutton _("History") action ShowMenu("history")
        textbutton _("Save") action ShowMenu("save")
        textbutton _("Load") action ShowMenu("load")
        textbutton _("Preferences") action ShowMenu("preferences")

        if renpy.variant("pc") or (renpy.variant("web") and not renpy.variant("mobile")):
            textbutton _("Back") action Rollback()

        textbutton _("History") action ShowMenu("history")
        textbutton _("Skip") action Skip() alternate Skip(fast=True, confirm=True)
        textbutton _("Auto") action Preference("auto-forward", "toggle")

        textbutton _("Save") action ShowMenu("save")
        textbutton _("Q.Save") action QuickSave()
        textbutton _("Q.Load") action QuickLoad()
        textbutton _("Prefs") action ShowMenu("preferences")

style navigation_button is gui_button
style navigation_button_text is gui_button_text

style navigation_button:
    size_group "navigation"
    properties gui.button_properties("navigation_button")

style navigation_button_text:
    properties gui.button_text_properties("navigation_button")

screen confirm(message, yes_action, no_action):
    modal True
    zorder 200
    style_prefix "confirm"

    add "gui/overlay/confirm.png"

    frame:
        vbox:
            xalign .5
            yalign .5
            spacing 30
            label _(message) style "confirm_prompt" xalign 0.5
            hbox:
                xalign .5
                spacing 100
                textbutton _("Yes") action yes_action
                textbutton _("No") action no_action

style confirm_frame:
    properties gui.frame_properties("confirm")

style confirm_prompt_text:
    properties gui.text_properties("confirm_prompt")

style confirm_button is gui_button
style confirm_button_text is gui_button_text

style confirm_button:
    properties gui.button_properties("confirm_button")

style confirm_button_text:
    properties gui.button_text_properties("confirm_button")

screen preferences():
    tag menu
    use game_menu(_("Preferences"), scroll="settings"):

        vbox:
            hbox:
                box_wrap True

                if renpy.variant("pc") or renpy.variant("web"):
                    vbox:
                        style_prefix "radio"
                        label _("Display")
                        textbutton _("Window") action Preference("display", "window")
                        textbutton _("Fullscreen") action Preference("display", "fullscreen")

                vbox:
                    style_prefix "check"
                    label _("Skip")
                    textbutton _("Unseen Text") action Preference("skip", "toggle")
                    textbutton _("After Choices") action Preference("after choices", "toggle")

            hbox:
                style_prefix "slider"
                label _("Text Speed")
                bar value Preference("text speed")

                label _("Auto-Forward Time")
                bar value Preference("auto-forward time")
