import fs from "node:fs";
import path from "node:path";
import type { GameBuilder, ExportInput, ExportResult, ExportStats } from "../common/export-types.js";
import { generateScript } from "./script-generator.js";
import { generateCharacters, generateCharacterImages } from "./character-generator.js";
import { generatePlaceholders } from "./asset-manager.js";
import { GUI_RPY, OPTIONS_RPY, SCREENS_RPY } from "./templates.js";

export class RenPyBuilder implements GameBuilder {
  async build(input: ExportInput): Promise<ExportResult> {
    const errors: string[] = [];
    const generatedFiles: string[] = [];
    const gameDir = path.join(input.outputDir, "game");

    // Create directory structure
    fs.mkdirSync(gameDir, { recursive: true });
    fs.mkdirSync(path.join(gameDir, "images"), { recursive: true });
    fs.mkdirSync(path.join(gameDir, "audio"), { recursive: true });

    const title = input.title;
    const safeName = title.replace(/[^a-zA-Z0-9一-鿿]/g, "_").replace(/_+/g, "_");

    try {
      // 1. Generate script.rpy
      const scriptContent = generateScript(input.scripts);
      const scriptPath = path.join(gameDir, "script.rpy");
      fs.writeFileSync(scriptPath, scriptContent, "utf-8");
      generatedFiles.push(scriptPath);

      // 2. Generate characters.rpy
      const charContent = generateCharacters(input.characters);
      const charImagesContent = generateCharacterImages(input.characters);
      const charPath = path.join(gameDir, "characters.rpy");
      fs.writeFileSync(charPath, charContent + "\n" + charImagesContent, "utf-8");
      generatedFiles.push(charPath);

      // 3. Write template files from embedded constants
      fs.writeFileSync(path.join(gameDir, "gui.rpy"), GUI_RPY, "utf-8");
      generatedFiles.push(path.join(gameDir, "gui.rpy"));
      fs.writeFileSync(path.join(gameDir, "options.rpy"), OPTIONS_RPY(title, safeName), "utf-8");
      generatedFiles.push(path.join(gameDir, "options.rpy"));
      fs.writeFileSync(path.join(gameDir, "screens.rpy"), SCREENS_RPY, "utf-8");
      generatedFiles.push(path.join(gameDir, "screens.rpy"));

      // 4. Generate placeholder assets
      const assetFiles = generatePlaceholders(input.scripts, input.characters, input.outputDir);
      generatedFiles.push(...assetFiles);

      // 5. Generate README
      const readme = this.generateReadme(title, input);
      const readmePath = path.join(input.outputDir, "README.md");
      fs.writeFileSync(readmePath, readme, "utf-8");
      generatedFiles.push(readmePath);

      // 6. Count stats
      const stats: ExportStats = {
        totalScenes: input.scripts.length,
        totalSteps: input.scripts.reduce((sum, s) => sum + s.steps.length, 0),
        totalCharacters: input.characters.length,
        generatedFiles,
      };

      return {
        success: true,
        outputPath: input.outputDir,
        stats,
      };
    } catch (err) {
      errors.push(err instanceof Error ? err.message : String(err));
      return {
        success: false,
        outputPath: input.outputDir,
        stats: { totalScenes: 0, totalSteps: 0, totalCharacters: 0, generatedFiles },
        errors,
      };
    }
  }

  private generateReadme(title: string, input: ExportInput): string {
    return `# ${title}

A visual novel generated by **All Novel Can Be Galgame**.

## How to Play

1. Download [Ren'Py SDK](https://www.renpy.org/latest.html)
2. Open Ren'Py Launcher
3. Click "Add Project" and select this directory
4. Click "Launch Project"

## Project Structure

- \`game/script.rpy\` - Main story script
- \`game/characters.rpy\` - Character definitions
- \`game/images/\` - Background and character art
- \`game/gui.rpy\` - GUI configuration
- \`game/options.rpy\` - Game options
- \`game/screens.rpy\` - Screen definitions

## Stats

- Scenes: ${input.scripts.length}
- Total Steps: ${input.scripts.reduce((s, sc) => s + sc.steps.length, 0)}
- Characters: ${input.characters.length}

## About

Generated from: "${title}"
Pipeline: All Novel Can Be Galgame (AI-driven visual novel generation platform)

---

*Replace placeholder images in \`game/images/\` with actual artwork for the final version.*
`;
  }
}
