import type { VNScript, VNStep, SayStep, ThoughtStep, BgStep, ShowStep, HideStep, NarrationStep, PauseStep, TransitionStep } from "@novel2gal/core";

/** Convert VNScript steps to Ren'Py script lines */
export function generateScript(scripts: VNScript[]): string {
  const lines: string[] = [];
  lines.push("# Auto-generated by All Novel Can Be Galgame");
  lines.push("# Do not edit manually");
  lines.push("");

  // Collect unique background IDs for image definitions
  const bgIds = new Set<string>();
  for (const script of scripts) {
    for (const step of script.steps) {
      if (step.type === "bg") bgIds.add((step as any).backgroundId);
    }
  }

  // Define background images
  if (bgIds.size > 0) {
    lines.push("# Background image definitions");
    for (const bgId of bgIds) {
      const safeId = sanitizeId(bgId);
      lines.push(`image bg ${safeId} = "images/bg/${safeId}.png"`);
    }
    lines.push("");
  }

  lines.push("label start:");
  lines.push("");

  let lastTransition: string | null = null;

  for (const script of scripts) {
    lines.push(`    # --- Scene: ${script.sceneId} ---`);
    lines.push("");

    for (const step of script.steps) {
      const withClause = lastTransition ? ` with ${lastTransition}` : "";
      lastTransition = null;

      switch (step.type) {
        case "bg":
          lines.push(`    scene bg ${sanitizeId((step as BgStep).backgroundId)}${withClause || " with fade"}`);
          break;

        case "show": {
          const s = step as ShowStep;
          const pos = s.position ? ` at ${s.position}` : "";
          const expr = s.expression ? ` ${sanitizeId(s.expression)}` : "";
          lines.push(`    show ${sanitizeId(s.characterId)}${expr} at center, character_display with dissolve`);
          break;
        }

        case "hide":
          lines.push(`    hide ${sanitizeId((step as HideStep).characterId)} with dissolve`);
          break;

        case "narration":
          lines.push(`    "${(step as NarrationStep).text}"${withClause}`);
          break;

        case "say": {
          const s = step as SayStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          lines.push(`    ${char} "${s.text}"${withClause}`);
          break;
        }

        case "thought": {
          const s = step as ThoughtStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          lines.push(`    ${char} "${s.text}" (what_prefix="«" what_suffix="»")${withClause}`);
          break;
        }

        case "pause":
          lines.push(`    pause ${(step as PauseStep).durationMs ? (step as PauseStep).durationMs! / 1000 : 1.0}`);
          break;

        case "transition": {
          const name = (step as TransitionStep).name || "fade";
          lastTransition = name;
          break;
        }
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** Sanitize an ID for use in Ren'Py (no special chars, underscore-separated) */
function sanitizeId(id: string): string {
  return id
    .replace(/[^a-zA-Z0-9_一-鿿]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}
