/** Embedded Ren'Py template files */

export const GUI_RPY = `# Ren'Py GUI configuration
# Auto-generated by All Novel Can Be Galgame

init python:
    gui.about = "Generated by All Novel Can Be Galgame"

define gui.text_font = "DejaVuSans.ttf"
define gui.name_text_size = 22
define gui.text_size = 22
define gui.label_text_size = 22
define gui.notify_text_size = 18
define gui.title_text_size = 75

define gui.textbox_height = 278
define gui.textbox_yalign = 1.0

define gui.choice_button_width = 1185
define gui.choice_button_height = None
define gui.choice_button_tile = False
define gui.choice_button_text_font = "DejaVuSans.ttf"
define gui.choice_button_text_size = 22
define gui.choice_button_text_xalign = 0.5
define gui.choice_button_text_idle_color = "#ffffffcc"
define gui.choice_button_text_hover_color = "#ffffff"

define gui.navigation_xpos = 60
define gui.skip_indicator = True
define gui.about = _("Powered by All Novel Can Be Galgame")
`;

export const OPTIONS_RPY = (title: string, safeName: string) => `# Game options
# Auto-generated by All Novel Can Be Galgame

define config.name = _("${title}")
define config.version = "1.0.0"

define gui.about = _("Generated by All Novel Can Be Galgame\\\\nBased on: ${title}")

define build.name = "${safeName}"
define build.directory = True
`;

export const SCREENS_RPY = `# Default screens
# Auto-generated by All Novel Can Be Galgame

screen say(who, what):
    style_prefix "say"
    window:
        id "window"
        if who is not None:
            window:
                id "namebox"
                style "namebox"
                text who id "who"
        text what id "what"
    if not renpy.variant("small"):
        add SideImage() xalign 0.0 yalign 1.0

style window:
    xalign 0.5
    xfill True
    yalign gui.textbox_yalign
    ysize gui.textbox_height

style say_dialogue:
    properties gui.text_properties("dialogue")
    xpos gui.text_xpos
    xsize gui.text_width
    ypos gui.text_ypos
    text_align gui.text_xalign

screen input(prompt):
    style_prefix "input"
    window:
        vbox:
            xanchor gui.text_xalign
            xpos gui.text_xpos
            xsize gui.text_width
            ypos gui.text_ypos
            text prompt style "input_prompt"
            input id "input"

screen choice(items):
    vbox:
        style_prefix "choice"
        for i in items:
            textbutton i.caption action i.action

style choice_vbox:
    xalign 0.5
    ypos 405
    yanchor 0.5
    spacing 45

screen navigation():
    vbox:
        style_prefix "navigation"
        xpos gui.navigation_xpos
        yalign 0.5
        spacing 6
        textbutton _("History") action ShowMenu("history")
        textbutton _("Save") action ShowMenu("save")
        textbutton _("Load") action ShowMenu("load")
        textbutton _("Preferences") action ShowMenu("preferences")
        textbutton _("Skip") action Skip() alternate Skip(fast=True, confirm=True)
        textbutton _("Auto") action Preference("auto-forward", "toggle")
        textbutton _("Q.Save") action QuickSave()
        textbutton _("Q.Load") action QuickLoad()

screen confirm(message, yes_action, no_action):
    modal True
    zorder 200
    style_prefix "confirm"
    add "gui/overlay/confirm.png"
    frame:
        vbox:
            xalign .5
            yalign .5
            spacing 30
            label _(message) style "confirm_prompt" xalign 0.5
            hbox:
                xalign .5
                spacing 100
                textbutton _("Yes") action yes_action
                textbutton _("No") action no_action
`;
